
        ##########################################################
        ### THIS FILE WAS AUTOGENERATED FROM JUPYTER ETL NOTEBOOK  ###
        ##########################################################

import dataverk as dv

conn = dv.connectors.JSONStatConnector()
df = conn.get_pandas_df('https://data.ssb.no/api/v0/no/table/08771')

df_alle = df[(df['næring (SN2007)']=='Alle næringar') & (df['statistikkvariabel']=='Ledige stillingar (stillingar)')]


dp = dv.Datapackage()


dp.add_resource(df_alle, dataset_name='Ledige stillinger', dataset_description="Antall ledige stillinger")
dp.add_resource(df, dataset_name='Ledige stillinger', dataset_description="Beskrivelse av Ledige stillinger")


dp.write_datapackage()